builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: "checksums.txt"
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: i386
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Tag }}"
